sylius_admin_currency:
    resource: |
        alias: sylius.currency
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        only: ['index', 'create']
        redirect: index
        grid: sylius_admin_currency
        form:
            type: Sylius\Bundle\Admin_Bundle\Form\Type\Currency_Type
        permission: true
    type: sylius.resource
