sylius_admin_customer_group:
    resource: |
        alias: sylius.customer_group
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_customer_group
        form:
            type: Sylius\Bundle\Admin_Bundle\Form\Type\Customer_Group_Type
        permission: true
    type: sylius.resource
