sylius_admin_product_option:
    resource: |
        alias: sylius.product_option
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_product_option
        form:
            type: Sylius\Bundle\Admin_Bundle\Form\Type\Product_Option_Type
        permission: true
    type: sylius.resource
