sylius_admin_shipping_category:
    resource: |
        alias: sylius.shipping_category
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_shipping_category
        form:
            type: Sylius\Bundle\Admin_Bundle\Form\Type\Shipping_Category_Type
        permission: true
    type: sylius.resource
