sylius_admin_tax_rate:
    resource: |
        alias: sylius.tax_rate
        section: admin
        templates: "@SyliusAdmin\\shared\\crud"
        except: ['show']
        redirect: update
        grid: sylius_admin_tax_rate
        form:
            type: Sylius\Bundle\Admin_Bundle\Form\Type\Tax_Rate_Type
        permission: true
    type: sylius.resource
