doctrine_migrations:
    services:
        'Doctrine\Migrations\Version\Migration_Factory': 'Sylius_Labs\Doctrine_Migrations_Extra_Bundle\Factory\Container_Aware_Version_Factory'
        'Doctrine\Migrations\Version\Comparator': 'Sylius_Labs\Doctrine_Migrations_Extra_Bundle\Comparator\Topological_Version_Comparator'
