# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

parameters:
    env(SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN): 'doctrine://default'
    env(SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN): 'doctrine://default?queue_name=main_failed'
    env(SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN): 'doctrine://default?queue_name=catalog_promotion_removal'
    env(SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN): 'doctrine://default?queue_name=catalog_promotion_removal_failed'

    sylius_messenger_transport_main_dsn: '%env(resolve:SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN)%'
    sylius_messenger_transport_main_failed_dsn: '%env(resolve:SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN)%'
    sylius_messenger_transport_catalog_promotion_removal_dsn: '%env(resolve:SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN)%'
    sylius_messenger_transport_catalog_promotion_removal_failed_dsn: '%env(resolve:SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN)%'

framework:
    messenger:
        transports:
            main:
                dsn: '%sylius_messenger_transport_main_dsn%'
                failure_transport: 'main_failed'
            main_failed:
                dsn: '%sylius_messenger_transport_main_failed_dsn%'
            catalog_promotion_removal:
                dsn: '%sylius_messenger_transport_catalog_promotion_removal_dsn%'
                failure_transport: 'catalog_promotion_removal_failed'
            catalog_promotion_removal_failed:
                dsn: '%sylius_messenger_transport_catalog_promotion_removal_failed_dsn%'
        routing:
            'Sylius\Bundle\Core_Bundle\Catalog_Promotion\Command\Apply_Catalog_Promotions_On_Variants': main
            'Sylius\Bundle\Core_Bundle\Catalog_Promotion\Command\Disable_Catalog_Promotion': main
            'Sylius\Bundle\Core_Bundle\Catalog_Promotion\Command\Remove_Catalog_Promotion': catalog_promotion_removal
            'Sylius\Bundle\Core_Bundle\Price_History\Command\Apply_Lowest_Price_On_Channel_Pricings': main
            'Sylius\Component\Promotion\Event\Catalog_Promotion_Created': main
            'Sylius\Component\Promotion\Event\Catalog_Promotion_Ended': main
            'Sylius\Component\Promotion\Event\Catalog_Promotion_Updated': main
        default_bus: sylius.command_bus
        buses:
            sylius.command_bus:
                middleware:
                    - 'validation'
                    - 'doctrine_transaction'
            sylius.query_bus:
                middleware:
                    - validation
            sylius.event_bus:
                default_middleware: allow_no_handlers
