sylius_test_plugin_main:
    path: /test/main
    controller: Symfony\Bundle\Framework_Bundle\Controller\Template_Controller::templateAction
    defaults:
        template: "@SyliusTestPlugin/main.html.twig"
