# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

parameters:
    env(SYLIUS_API_AUTHORIZATION_HEADER): Authorization
    sylius.api.authorization_header: "%env(resolve:SYLIUS_API_AUTHORIZATION_HEADER)%"
    sylius.api.doctrine.orm.query.extension.shop.order.filter_cart.allowed_operations:
        - "sylius_api_shop_order_get"
        - "sylius_api_shop_order_payment_get_configuration"
        - "sylius_api_shop_order_payment_patch"
        - "sylius_api_shop_order_payment_patch_account"
    sylius.security.api_route: "/api/v2"
    sylius.security.api_regex: "^%sylius.security.api_route%"
    sylius.security.api_admin_route: "%sylius.security.api_route%/admin"
    sylius.security.api_admin_regex: "^%sylius.security.api_admin_route%"
    sylius.security.api_shop_route: "%sylius.security.api_route%/shop"
    sylius.security.api_shop_regex: "^%sylius.security.api_shop_route%"
    sylius.security.api_shop_account_route: "%sylius.security.api_shop_route%/account"
    sylius.security.api_shop_account_regex: "^%sylius.security.api_shop_account_route%"

sylius_api:
    filter_eager_loading_extension:
        restricted_resources:
            '%sylius.model.product.class%':
                operations:
                    sylius_api_shop_product_get_collection: ~
    order_states_to_filter_out:
        - !php/const Sylius\Component\Core\Model\Order_Interface::STATE_CART

api_platform:
    serializer:
        hydra_prefix: true
    use_symfony_listeners: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    patch_formats:
        json: ['application/merge-patch+json']
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: "%sylius.api.authorization_header%"
                type: header
    exception_to_status:
        # Default API Platform exception to status code mapping
        Api_Platform\Exception\Filter_Validation_Exception: 400
        Api_Platform\Metadata\Exception\Invalid_Argument_Exception: 400
        Api_Platform\Validator\Exception\Validation_Exception: 422
        Doctrine\ORM\Optimistic_Lock_Exception: 409
        Symfony\Component\Serializer\Exception\Missing_Constructor_Arguments_Exception: 422
        Symfony\Component\Serializer\Exception\Exception_Interface: 400

        # Sylius exception to status code mapping
        Sylius\Abstraction\State_Machine\Exception\State_Machine_Execution_Exception: 422
        Sylius\Bundle\Api_Bundle\Exception\Channel_Pricing_Channel_Code_Mismatch_Exception: 422
        Sylius\Bundle\Api_Bundle\Exception\Invalid_Product_Attribute_Value_Type_Exception: 422
        Sylius\Bundle\Api_Bundle\Exception\Invalid_Request_Argument_Exception: 400
        Sylius\Bundle\Api_Bundle\Exception\Locale_Is_Used_Exception: 422
        Sylius\Component\Payment\Exception\Payment_Request_Not_Found_Exception: 404
        Sylius\Bundle\Api_Bundle\Exception\Payment_Not_Found_Exception: 404
        Sylius\Bundle\Api_Bundle\Exception\Payment_Method_Not_Found_Exception: 404
        Sylius\Bundle\Api_Bundle\Exception\State_Machine_Transition_Failed_Exception: 422
        Sylius\Bundle\Api_Bundle\Exception\Translation_In_Default_Locale_Cannot_Be_Removed: 422
        Sylius\Bundle\Api_Bundle\Exception\Translation_Locale_Mismatch_Exception: 422
        Sylius\Bundle\Api_Bundle\Exception\Cannot_Remove_Menu_Taxon_Exception: 409
        Sylius\Bundle\User_Bundle\Exception\User_Not_Found_Exception: 404
        Sylius\Component\Core\Exception\Resource_Delete_Exception: 422
        Sylius\Component\Core\Inventory\Exception\Not_Enough_Units_On_Hand_Exception: 422
        Sylius\Component\Core\Inventory\Exception\Not_Enough_Units_On_Hold_Exception: 422
        Sylius\Component\Payment\Exception\Invalid_Payment_Request_Payload_Exception: 422
        Sylius\Component\Promotion\Exception\Failed_Generation_Exception: 422
        Symfony\Component\Serializer\Exception\Unexpected_Value_Exception: 400
        Sylius\Bundle\Api_Bundle\Command_Handler\Checkout\Exception\Order_Total_Has_Changed_Exception: 409
        Sylius\Bundle\Api_Bundle\Serializer\Exception\Invalid_Amount_Type_Exception: 400
    defaults:
        normalization_context:
            skip_null_values: false
        pagination_client_items_per_page: true
        extra_properties:
            rfc_7807_compliant_errors: true
            standard_put: false

lexik_jwt_authentication:
    api_platform:
        check_path: "%sylius.security.api_route%/administrators/token"
        username_path: email
        password_path: password
