# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_order:
    resources:
        adjustment:
            classes:
                model: Sylius\Component\Core\Model\Adjustment
        order:
            classes:
                model: Sylius\Component\Core\Model\Order
                controller: Sylius\Bundle\Core_Bundle\Controller\Order_Controller
                repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\Order_Repository
        order_item:
            classes:
                model: Sylius\Component\Core\Model\Order_Item
                repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\Order_Item_Repository
        order_item_unit:
            classes:
                model: Sylius\Component\Core\Model\Order_Item_Unit
                repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\Order_Item_Unit_Repository
        order_sequence:
            classes:
                model: Sylius\Component\Core\Model\Order_Sequence
