# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_user:
    resources:
        admin:
            user:
                classes:
                    model: Sylius\Component\Core\Model\Admin_User
                    interface: Sylius\Component\Core\Model\Admin_User_Interface
                    repository: Sylius\Bundle\User_Bundle\Doctrine\ORM\User_Repository
                    form: Sylius\Bundle\Core_Bundle\Form\Type\User\Admin_User_Type
        shop:
            user:
                classes:
                    model: Sylius\Component\Core\Model\Shop_User
                    interface: Sylius\Component\Core\Model\Shop_User_Interface
                    repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\User_Repository
                    form: Sylius\Bundle\Core_Bundle\Form\Type\User\Shop_User_Type
        oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\User_O_Auth
                    interface: Sylius\Component\User\Model\User_O_Auth_Interface
                    controller: Sylius\Bundle\Resource_Bundle\Controller\Resource_Controller
