# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_review:
    resources:
        product:
            subject: "%sylius.model.product.class%"
            review:
                classes:
                    model: Sylius\Component\Core\Model\Product_Review
                    repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\Product_Review_Repository
                    form: Sylius\Bundle\Core_Bundle\Form\Type\Product\Product_Review_Type
            reviewer:
                classes:
                    model: "%sylius.model.customer.class%"
