# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

sylius_payment:
    resources:
        payment:
            classes:
                model: Sylius\Component\Core\Model\Payment
                repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\Payment_Repository
        payment_method:
            classes:
                model: Sylius\Component\Core\Model\Payment_Method
                repository: Sylius\Bundle\Core_Bundle\Doctrine\ORM\Payment_Method_Repository
                controller: Sylius\Bundle\Core_Bundle\Controller\Payment_Method_Controller
