imports:
    - { resource: "../src/Sylius/Behat/Resources/config/services.xml" }

# workaround needed for strange "test.client.history" problem
# see https://github.com/FriendsOfBehat/SymfonyExtension/issues/88
services:
    Symfony\Component\Browser_Kit\Abstract_Browser: '@test.client'
