# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

doctrine:
    orm:
        dql:
            string_functions:
                JSONB_ARRAY_ELEMENTS_TEXT: Sylius\Bundle\Product_Bundle\Doctrine\ORM\Query\AST\Function\Jsonb_Array_Elements_Text
