# This file is part of the Sylius package.
# (c) Sylius Sp. z o.o.

parameters:
    sylius_order.resend_order_confirmation_email.order_states:
        - !php/const Sylius\Component\Order\Model\Order_Interface::STATE_NEW
        - !php/const Sylius\Component\Order\Model\Order_Interface::STATE_FULFILLED

twig:
    globals:
        sylius_order_states_that_allows_to_resend_order_confirmation_email: "%sylius_order.resend_order_confirmation_email.order_states%"

