framework:
    workflows:
        !php/const Sylius\Component\Payment\Payment_Transitions::GRAPH:
            type: state_machine
            marking_store:
                type: method
                property: state
            supports:
                - Sylius\Component\Core\Model\Payment_Interface
            initial_marking: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_CART
            places:
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_CART
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_PROCESSING
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_AUTHORIZED
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_COMPLETED
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_FAILED
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_CANCELLED
                - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_REFUNDED
            transitions:
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_CREATE:
                    from: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_CART
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_PROCESS:
                    from: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_PROCESSING
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_AUTHORIZE:
                    from:
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_PROCESSING
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_AUTHORIZED
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_COMPLETE:
                    from:
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_PROCESSING
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_AUTHORIZED
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_COMPLETED
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_FAIL:
                    from:
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_PROCESSING
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_AUTHORIZED
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_FAILED
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_CANCEL:
                    from:
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_NEW
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_PROCESSING
                        - !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_AUTHORIZED
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_CANCELLED
                !php/const Sylius\Component\Payment\Payment_Transitions::TRANSITION_REFUND:
                    from: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_COMPLETED
                    to: !php/const Sylius\Component\Payment\Model\Payment_Interface::STATE_REFUNDED
