framework:
    workflows:
        !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_Transitions::GRAPH:
            type: state_machine
            marking_store:
                type: method
                property: state
            supports:
                - Sylius\Component\Core\Model\Catalog_Promotion_Interface
            initial_marking: !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_INACTIVE
            places:
                - !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_INACTIVE
                - !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_PROCESSING
                - !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_ACTIVE
            transitions:
                !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_Transitions::TRANSITION_PROCESS:
                    from:
                        - !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_INACTIVE
                        - !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_ACTIVE
                    to: !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_PROCESSING
                !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_Transitions::TRANSITION_ACTIVATE:
                    from: !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_PROCESSING
                    to: !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_ACTIVE
                !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_Transitions::TRANSITION_DEACTIVATE:
                    from: !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_PROCESSING
                    to: !php/const Sylius\Component\Promotion\Model\Catalog_Promotion_States::STATE_INACTIVE
