framework:
    workflows:
        sylius_product_review:
            type: state_machine
            marking_store:
                type: method
                property: status
            supports:
                - Sylius\Component\Core\Model\Product_Review_Interface
            initial_marking: !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_NEW
            places:
                - !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_NEW
                - !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_ACCEPTED
                - !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_REJECTED
            transitions:
                !php/const Sylius\Component\Core\Product_Review_Transitions::TRANSITION_ACCEPT:
                    from: !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_NEW
                    to: !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_ACCEPTED
                !php/const Sylius\Component\Core\Product_Review_Transitions::TRANSITION_REJECT:
                    from: !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_NEW
                    to: !php/const Sylius\Component\Review\Model\Review_Interface::STATUS_REJECTED
