framework:
    workflows:
        !php/const Sylius\Component\Core\Order_Checkout_Transitions::GRAPH:
            type: state_machine
            marking_store:
                type: method
                property: checkoutState
            supports:
                - Sylius\Component\Core\Model\Order_Interface
            initial_marking: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_CART
            places:
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_CART
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_ADDRESSED
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SELECTED
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SKIPPED
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SELECTED
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SKIPPED
                - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_COMPLETED
            transitions:
                !php/const Sylius\Component\Core\Order_Checkout_Transitions::TRANSITION_ADDRESS:
                    from: 
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_CART
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_ADDRESSED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SKIPPED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SKIPPED
                    to: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_ADDRESSED
                !php/const Sylius\Component\Core\Order_Checkout_Transitions::TRANSITION_SKIP_SHIPPING:
                    from:
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_ADDRESSED
                    to: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SKIPPED
                !php/const Sylius\Component\Core\Order_Checkout_Transitions::TRANSITION_SELECT_SHIPPING:
                    from:
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_ADDRESSED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SKIPPED
                    to: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SELECTED
                !php/const Sylius\Component\Core\Order_Checkout_Transitions::TRANSITION_SKIP_PAYMENT:
                    from:
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SKIPPED
                    to: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SKIPPED
                !php/const Sylius\Component\Core\Order_Checkout_Transitions::TRANSITION_SELECT_PAYMENT:
                    from:
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SKIPPED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_SHIPPING_SELECTED
                    to: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SELECTED
                !php/const Sylius\Component\Core\Order_Checkout_Transitions::TRANSITION_COMPLETE:
                    from:
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SELECTED
                        - !php/const Sylius\Component\Core\Order_Checkout_States::STATE_PAYMENT_SKIPPED
                    to: !php/const Sylius\Component\Core\Order_Checkout_States::STATE_COMPLETED
