<?php

/*
 * This file is part of the Sylius package.
 *
 * (c) Sylius Sp. z o.o.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare (strict_types=1);
use Sylius\Behat\Context\Ui\Admin\Browsing_Catalog_Promotion_Product_Variants_Context;
use Sylius\Behat\Context\Ui\Admin\Browsing_Product_Variants_Context;
use Sylius\Behat\Context\Ui\Admin\Channel_Pricing_Log_Entry_Context;
use Sylius\Behat\Context\Ui\Admin\Dashboard_Context;
use Sylius\Behat\Context\Ui\Admin\Error_Page_Context;
use Sylius\Behat\Context\Ui\Admin\Impersonating_Customers_Context;
use Sylius\Behat\Context\Ui\Admin\Locale_Context;
use Sylius\Behat\Context\Ui\Admin\Login_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Administrator_Locales_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Administrators_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Catalog_Promotions_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Channels_Billing_Data_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Channels_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Countries_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Currencies_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Customer_Groups_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Customers_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Exchange_Rates_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Inventory_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Locales_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Orders_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Payment_Methods_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Payment_Requests_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Payments_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Association_Types_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Attributes_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Options_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Reviews_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Products_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Taxons_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Variants_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Product_Variants_Prices_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Promotion_Coupons_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Promotions_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Shipments_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Shipping_Categories_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Shipping_Methods_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Tax_Categories_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Taxons_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Tax_Rate_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Translatable_Entities_Context;
use Sylius\Behat\Context\Ui\Admin\Managing_Zones_Context;
use Sylius\Behat\Context\Ui\Admin\Navigating_Between_Product_Show_And_Edit_Pages_Context;
use Sylius\Behat\Context\Ui\Admin\Notification_Context;
use Sylius\Behat\Context\Ui\Admin\Order_History_Context;
use Sylius\Behat\Context\Ui\Admin\Product_Creation_Context;
use Sylius\Behat\Context\Ui\Admin\Product_Show_Page_Context;
use Sylius\Behat\Context\Ui\Admin\Product_Variants_Creation_Context;
use Sylius\Behat\Context\Ui\Admin\Removing_Product_Context;
use Sylius\Behat\Context\Ui\Admin\Removing_Taxon_Context;
use Sylius\Behat\Context\Ui\Admin\Resetting_Password_Context;
use Sylius\Behat\Context\Ui\Admin\Search_Filter_Context;
use Sylius\Behat\Element\Admin\Catalog_Promotion\Filter_Element;
use Sylius\Behat\Element\Admin\Catalog_Promotion\Form_Element;
use Sylius\Behat\Element\Admin\Channel\Discounted_Products_Checking_Period_Input_Element_Interface;
use Sylius\Behat\Element\Admin\Channel\Exclude_Taxons_From_Showing_Lowest_Price_Input_Element_Interface;
use Sylius\Behat\Element\Admin\Channel\Lowest_Price_Flag_Element_Interface;
use Sylius\Behat\Element\Admin\Promotion\Form_Element_Interface;
use Sylius\Behat\Element\Admin\Tax_Rate\Filter_Element as TaxRateFilterElement;
use Symfony\Component\Dependency_Injection\Loader\Configurator\Container_Configurator;
use function Symfony\Component\Dependency_Injection\Loader\Configurator\service;
return static function (Container_Configurator $container): void {
    $services = $container->services();
    $services->defaults()->public();
    $services->set('sylius.behat.context.ui.admin.dashboard', Dashboard_Context::class)->args([service('sylius.behat.page.admin.dashboard')]);
    $services->set('sylius.behat.context.ui.admin.error_page', Error_Page_Context::class)->args([service('sylius.behat.page.error')]);
    $services->set('sylius.behat.context.ui.admin.locale', Locale_Context::class)->args([service('sylius.behat.page.admin.dashboard'), service('translator'), service('sylius.behat.page.admin.administrator.create')]);
    $services->set('sylius.behat.context.ui.admin.login', Login_Context::class)->args([service('sylius.behat.page.admin.dashboard'), service('sylius.behat.page.admin.login')]);
    $services->set('sylius.behat.context.ui.admin.managing_administrators', Managing_Administrators_Context::class)->args([service('sylius.behat.page.admin.administrator.create'), service('sylius.behat.page.admin.administrator.index'), service('sylius.behat.page.admin.administrator.update'), service('sylius.behat.element.admin.top_bar'), service('sylius.behat.notification_checker.admin'), service('sylius.repository.admin_user'), service('sylius.behat.shared_storage')]);
    $services->set('sylius.behat.context.ui.admin.managing_administrator_locale', Managing_Administrator_Locales_Context::class)->args([service('sylius.behat.page.admin.administrator.update'), service('sylius.behat.shared_storage')]);
    $services->set(Managing_Catalog_Promotions_Context::class)->args([service('sylius.behat.page.admin.catalog_promotion.index'), service('sylius.behat.page.admin.catalog_promotion.create'), service('sylius.behat.page.admin.catalog_promotion.update'), service('sylius.behat.page.admin.catalog_promotion.show'), service(Form_Element::class), service(Filter_Element::class), service('sylius.behat.shared_storage'), service('sylius.behat.notification_checker.admin')]);
    $services->set(Browsing_Catalog_Promotion_Product_Variants_Context::class)->args([service('sylius.behat.page.admin.catalog_promotion.product_variant.index'), service('sylius.behat.page.admin.product.show_page')]);
    $services->set('sylius.behat.context.ui.admin.managing_channels', Managing_Channels_Context::class)->args([service('sylius.behat.page.admin.channel.index'), service('sylius.behat.page.admin.channel.create'), service('sylius.behat.page.admin.channel.update'), service('sylius.behat.element.admin.channel.shipping_address_in_checkout_required'), service('sylius.behat.current_page_resolver'), service('sylius.behat.notification_checker.admin'), service(Discounted_Products_Checking_Period_Input_Element_Interface::class), service(Lowest_Price_Flag_Element_Interface::class), service(Exclude_Taxons_From_Showing_Lowest_Price_Input_Element_Interface::class)]);
    $services->set('sylius.behat.context.ui.admin.managing_channels_billing_data', Managing_Channels_Billing_Data_Context::class)->args([service('sylius.behat.element.admin.channel.shop_billing_data')]);
    $services->set('sylius.behat.context.ui.admin.managing_countries', Managing_Countries_Context::class)->args([service('sylius.behat.page.admin.country.index'), service('sylius.behat.page.admin.country.create'), service('sylius.behat.page.admin.country.update'), service('sylius.behat.current_page_resolver'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.managing_currencies', Managing_Currencies_Context::class)->args([service('sylius.behat.page.admin.currency.index'), service('sylius.behat.page.admin.currency.create'), service('sylius.behat.element.admin.currency.form')]);
    $services->set('sylius.behat.context.ui.admin.managing_customers', Managing_Customers_Context::class)->args([service('sylius.behat.page.admin.customer.create'), service('sylius.behat.page.admin.customer.index'), service('sylius.behat.page.admin.customer.update'), service('sylius.behat.page.admin.customer.show'), service('sylius.behat.page.admin.customer.order_index'), service('sylius.behat.current_page_resolver'), service('sylius.behat.element.admin.customer.form')]);
    $services->set('sylius.behat.context.ui.admin.managing_customer_groups', Managing_Customer_Groups_Context::class)->args([service('sylius.behat.page.admin.customer_group.create'), service('sylius.behat.page.admin.customer_group.index'), service('sylius.behat.page.admin.customer_group.update'), service('sylius.behat.element.admin.customer_group.form')]);
    $services->set('sylius.behat.context.ui.admin.managing_exchange_rates', Managing_Exchange_Rates_Context::class)->args([service('sylius.behat.page.admin.exchange_rate.create'), service('sylius.behat.page.admin.exchange_rate.index'), service('sylius.behat.page.admin.exchange_rate.update'), service('sylius.behat.element.admin.exchange_rate.form')]);
    $services->set('sylius.behat.context.ui.admin.managing_inventory', Managing_Inventory_Context::class)->args([service('sylius.behat.page.admin.inventory.index')]);
    $services->set('sylius.behat.context.ui.admin.managing_locales', Managing_Locales_Context::class)->args([service('sylius.behat.page.admin.locale.create'), service('sylius.behat.page.admin.locale.index'), service('sylius.behat.element.admin.locale.form'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.managing_orders', Managing_Orders_Context::class)->args([service('sylius.behat.shared_storage'), service('sylius.behat.page.admin.order.index'), service('sylius.behat.page.admin.order.show'), service('sylius.behat.page.admin.order.update'), service('sylius.behat.page.error'), service('sylius.behat.notification_checker.admin'), service('sylius.behat.shared_security')]);
    $services->set('sylius.behat.context.ui.admin.order_history', Order_History_Context::class)->args([service('sylius.behat.page.admin.order.history')]);
    $services->set('sylius.behat.context.ui.admin.managing_payments', Managing_Payments_Context::class)->args([service('sylius.behat.page.admin.payment.index'), service('sylius.behat.page.admin.order.show'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.managing_shipments', Managing_Shipments_Context::class)->args([service('sylius.behat.page.admin.shipment.index'), service('sylius.behat.page.admin.order.show'), service('sylius.behat.notification_checker.admin'), service('sylius.behat.page.admin.shipment.show')]);
    $services->set('sylius.behat.context.ui.admin.managing_payment_methods', Managing_Payment_Methods_Context::class)->args([service('sylius.behat.page.admin.payment_method.create'), service('sylius.behat.page.admin.payment_method.index'), service('sylius.behat.page.admin.payment_method.update'), service('sylius.behat.current_page_resolver'), ['offline' => 'Offline']]);
    $services->set('sylius.behat.context.ui.admin.product_showpage', Product_Show_Page_Context::class)->args([service('sylius.behat.page.admin.product.index'), service('sylius.behat.page.admin.product.show_page'), service('sylius.behat.element.product.show.associations'), service('sylius.behat.element.product.show.attributes'), service('sylius.behat.element.product.show.details'), service('sylius.behat.element.product.show.media'), service('sylius.behat.element.product.show.more_details'), service('sylius.behat.element.product.show.pricing'), service('sylius.behat.element.product.show.shipping'), service('sylius.behat.element.product.show.taxonomy'), service('sylius.behat.element.product.show.options'), service('sylius.behat.element.product.show.variants'), service('router')]);
    $services->set('sylius.behat.context.ui.admin.managing_products', Managing_Products_Context::class)->args([service('sylius.behat.shared_storage'), service('sylius.behat.page.admin.product.create_simple'), service('sylius.behat.page.admin.product.create_configurable'), service('sylius.behat.page.admin.product.index'), service('sylius.behat.page.admin.product.update_simple'), service('sylius.behat.page.admin.product.update_configurable'), service('sylius.behat.page.admin.product_review.index'), service('sylius.behat.page.admin.product.index_per_taxon'), service('sylius.behat.page.admin.product_variant.create'), service('sylius.behat.page.admin.product_variant.generate'), service('sylius.behat.current_page_resolver'), service('sylius.behat.notification_checker.admin'), service('sylius.behat.page.admin.product_variant.update'), service('sylius.behat.java_script_test_helper'), service('sylius.behat.element.admin.product.association_form'), service('sylius.behat.element.admin.product.attributes_form'), service('sylius.behat.element.admin.product.channel_pricing_form'), service('sylius.behat.element.admin.product.media_form'), service('sylius.behat.element.admin.product.taxonomy_form'), service('sylius.behat.element.admin.product.translations_form')]);
    $services->set('sylius.behat.context.ui.admin.managing_product_association_types', Managing_Product_Association_Types_Context::class)->args([service('sylius.behat.page.admin.product_association_type.create'), service('sylius.behat.page.admin.product_association_type.index'), service('sylius.behat.page.admin.product_association_type.update'), service('sylius.behat.element.admin.product_association_type.form'), service('sylius.behat.shared_storage')]);
    $services->set('sylius.behat.context.ui.admin.managing_product_attributes', Managing_Product_Attributes_Context::class)->args([service('sylius.behat.page.admin.product_attribute.create'), service('sylius.behat.page.admin.product_attribute.index'), service('sylius.behat.page.admin.product_attribute.update'), service('sylius.behat.element.admin.product_attribute.form'), service('sylius.behat.element.admin.product_attribute.filter')]);
    $services->set('sylius.behat.context.ui.admin.managing_product_options', Managing_Product_Options_Context::class)->args([service('sylius.behat.page.admin.product_option.index'), service('sylius.behat.page.admin.product_option.create'), service('sylius.behat.page.admin.product_option.update'), service('sylius.behat.element.admin.product_option.form'), service('sylius.behat.shared_storage')]);
    $services->set('sylius.behat.context.ui.admin.managing_product_reviews', Managing_Product_Reviews_Context::class)->args([service('sylius.behat.page.admin.product_review.index'), service('sylius.behat.page.admin.product_review.update'), service('sylius.behat.notification_checker.admin')]);
    $services->set(Managing_Product_Taxons_Context::class)->args([service('sylius.behat.page.admin.product.update_simple'), service('sylius.behat.element.admin.product.taxonomy_form')]);
    $services->set('sylius.behat.context.ui.admin.managing_product_variants', Managing_Product_Variants_Context::class)->args([service('sylius.behat.shared_storage'), service('sylius.behat.page.admin.product_variant.create'), service('sylius.behat.page.admin.product_variant.index'), service('sylius.behat.page.admin.product_variant.update'), service('sylius.behat.page.admin.product_variant.generate'), service('sylius.behat.current_page_resolver'), service('sylius.behat.notification_checker.admin')]);
    $services->set(Managing_Product_Variants_Prices_Context::class)->args([service('sylius.behat.page.admin.product_variant.update')]);
    $services->set('sylius.behat.context.ui.admin.browsing_product_variants', Browsing_Product_Variants_Context::class)->args([service('sylius.behat.page.admin.product_variant.index'), service('sylius.resolver.product_variant')]);
    $services->set('sylius.behat.context.ui.admin.managing_promotions', Managing_Promotions_Context::class)->args([service('sylius.behat.shared_storage'), service('sylius.behat.page.admin.promotion.index'), service('sylius.behat.page.admin.promotion_coupon.index'), service('sylius.behat.page.admin.promotion.create'), service('sylius.behat.page.admin.promotion.update'), service('sylius.behat.current_page_resolver'), service('sylius.behat.notification_checker.admin'), service(Form_Element_Interface::class)]);
    $services->set('sylius.behat.context.ui.admin.managing_promotion_coupons', Managing_Promotion_Coupons_Context::class)->args([service('sylius.behat.page.admin.promotion_coupon.create'), service('sylius.behat.page.admin.promotion_coupon.generate'), service('sylius.behat.page.admin.promotion_coupon.index'), service('sylius.behat.page.admin.promotion_coupon.update'), service('sylius.behat.element.admin.promotion_coupon.form'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.managing_shipping_methods', Managing_Shipping_Methods_Context::class)->args([service('sylius.behat.page.admin.shipping_method.index'), service('sylius.behat.page.admin.shipping_method.create'), service('sylius.behat.page.admin.shipping_method.update'), service('sylius.behat.element.admin.shipping_method.form'), service('sylius.behat.shared_storage')]);
    $services->set('sylius.behat.context.ui.admin.managing_shipping_categories', Managing_Shipping_Categories_Context::class)->args([service('sylius.behat.page.admin.shipping_category.index'), service('sylius.behat.page.admin.shipping_category.create'), service('sylius.behat.page.admin.shipping_category.update')]);
    $services->set('sylius.behat.context.ui.admin.managing_tax_categories', Managing_Tax_Categories_Context::class)->args([service('sylius.behat.page.admin.tax_category.index'), service('sylius.behat.page.admin.tax_category.create'), service('sylius.behat.page.admin.tax_category.update'), service('sylius.behat.element.admin.tax_category.form')]);
    $services->set('sylius.behat.context.ui.admin.managing_translatable_entities', Managing_Translatable_Entities_Context::class)->args([service('sylius.behat.page.admin.taxon.create'), service('sylius.behat.element.admin.taxon.form')]);
    $services->set('sylius.behat.context.ui.admin.managing_taxons', Managing_Taxons_Context::class)->args([service('sylius.behat.shared_storage'), service('sylius.behat.page.admin.taxon.create'), service('sylius.behat.page.admin.taxon.create_for_parent'), service('sylius.behat.page.admin.taxon.update'), service('sylius.behat.element.admin.taxon.form'), service('sylius.behat.element.admin.taxon.image_form'), service('sylius.behat.element.admin.taxon.tree'), service('sylius.behat.notification_checker.admin'), service('sylius.behat.java_script_test_helper'), service('sylius.behat.page.admin.product.update_simple'), service('sylius.behat.element.admin.product.taxonomy_form')]);
    $services->set('sylius.behat.context.ui.admin.managing_tax_rate', Managing_Tax_Rate_Context::class)->args([service('sylius.behat.page.admin.tax_rate.index'), service('sylius.behat.page.admin.tax_rate.create'), service('sylius.behat.page.admin.tax_rate.update'), service('sylius.behat.current_page_resolver'), service(Tax_Rate_Filter_Element::class)]);
    $services->set('sylius.behat.context.ui.admin.managing_zones', Managing_Zones_Context::class)->args([service('sylius.behat.page.admin.zone.index'), service('sylius.behat.page.admin.zone.create'), service('sylius.behat.page.admin.zone.update'), service('sylius.behat.element.admin.zone.form'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.notification', Notification_Context::class)->args([service('sylius.behat.element.admin.notifications')]);
    $services->set('sylius.behat.context.ui.admin.impersonating_customers', Impersonating_Customers_Context::class)->args([service('sylius.behat.page.admin.customer.show'), service('sylius.behat.page.admin.dashboard'), service('sylius.behat.page.shop.home'), service('sylius.behat.page.admin.impersonate_user'), service('sylius.behat.notification_checker.admin')]);
    $services->set(Removing_Product_Context::class)->args([service('sylius.behat.shared_storage'), service('sylius.behat.page.admin.product.index'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.removing_taxons', Removing_Taxon_Context::class)->args([service('sylius.behat.page.admin.taxon.create'), service('sylius.behat.element.admin.taxon.tree'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.resetting_password', Resetting_Password_Context::class)->args([service('sylius.behat.page.admin.request_password_reset'), service('sylius.behat.page.admin.reset_password'), service('sylius.behat.element.admin.account.reset'), service('sylius.behat.notification_checker.admin')]);
    $services->set('sylius.behat.context.ui.admin.navigating_between_product_show_and_edit_pages_context', Navigating_Between_Product_Show_And_Edit_Pages_Context::class)->args([service('sylius.behat.page.admin.product.update_simple'), service('sylius.behat.page.admin.product_variant.update'), service('sylius.behat.page.admin.product.show_page'), service('sylius.behat.page.admin.product.create_simple'), service('sylius.behat.page.admin.product.create_configurable')]);
    $services->set(Product_Creation_Context::class)->args([service('sylius.behat.page.admin.product.create_simple'), service('sylius.behat.element.admin.product.translations_form'), service('sylius.behat.element.admin.product.channel_pricing_form'), service('sylius.behat.element.admin.product.taxonomy_form')]);
    $services->set(Product_Variants_Creation_Context::class)->args([service('sylius.behat.page.admin.product_variant.create')]);
    $services->set(Channel_Pricing_Log_Entry_Context::class)->args([service('sylius.behat.page.admin.channel_pricing_log_entry.index')]);
    $services->set('sylius.behat.context.ui.admin.search_filter', Search_Filter_Context::class)->args([service('sylius.behat.element.admin.crud.index.search_filter')]);
    $services->set('sylius.behat.context.ui.admin.managing_payment_requests', Managing_Payment_Requests_Context::class)->args([service('sylius.behat.page.admin.payment.payment_request.index'), service('sylius.behat.page.admin.payment.payment_request.show'), service('sylius.repository.payment_request'), service('sylius.behat.shared_storage'), service('sylius.behat.shared_security')]);
};