framework:
    workflows:
        !php/const Sylius\Component\Shipping\Shipment_Transitions::GRAPH:
            type: state_machine
            marking_store:
                type: method
                property: shippingState
            supports:
                - Sylius\Component\Shipping\Model\Shipment_Interface
            initial_marking: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_CART
            places:
                - !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_CART
                - !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_READY
                - !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_SHIPPED
                - !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_CANCELLED
            transitions:
                !php/const Sylius\Component\Shipping\Shipment_Transitions::TRANSITION_CREATE:
                    from: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_CART
                    to: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_READY
                !php/const Sylius\Component\Shipping\Shipment_Transitions::TRANSITION_SHIP:
                    from: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_READY
                    to: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_SHIPPED
                !php/const Sylius\Component\Shipping\Shipment_Transitions::TRANSITION_CANCEL:
                    from: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_READY
                    to: !php/const Sylius\Component\Shipping\Model\Shipment_Interface::STATE_CANCELLED
